name: Push 100 Empty Commits

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch.

jobs:
  empty-commits:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner.

    steps:
      # Step 1: Set up Git user with your details
      - name: Set up Git user
        run: |
          git config --global user.name "Runarok"  # Your name
          git config --global user.email "RunarokHrafn@gmail.com"  # Your email

      # Step 2: Checkout the repository to make changes
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository.
        with:
          persist-credentials: false  # Avoid storing credentials permanently.
          fetch-depth: 0  # Fetch the full history to avoid issues with git operations.

      # Step 3: Pull latest changes from the remote repository
      - name: Pull latest changes
        run: |
          git pull origin main  # Ensure the local branch is up-to-date with the remote.

      # Step 4: Create a new branch (optional) and make 100 empty commits
      - name: Create empty commits
        run: |
          git checkout -b Empty-commits  # Create and checkout a new branch 'Empty-commits'.
          for i in $(seq 1 100); do
            git commit --allow-empty -m "Empty commit #$i"  # Create an empty commit with a unique message.
          done

      # Step 5: Remove all files after 100 empty commits
      - name: Remove all files after 100 empty commits
        run: |
          git rm -rf .  # Remove all files in the current directory.
          git commit -m "Remove all files after 100 empty commits"  # Commit the file removal.

      # Step 4: Delete the 'Empty-commits' branch if it exists
      - name: Delete Empty-commits branch
        run: |
          git branch -D Empty-commits || echo "Branch 'Empty-commits' does not exist locally."
          git push origin --delete Empty-commits || echo "Branch 'Empty-commits' does not exist on remote."

      # Step 6: Push commits to the remote repository with GitHub token for authentication
      - name: Push commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication.
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git Empty-commits
