name: Push 100 Empty Commits

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch.

jobs:
  empty-commits:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner.

    steps:
      # Step 1: Set up Git user with your details
      - name: Set up Git user
        run: |
          git config --global user.name "Runarok"  # Your name
          git config --global user.email "RunarokHrafn@gmail.com"  # Your email

      # Step 2: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository.
        with:
          persist-credentials: false  # Avoid storing credentials permanently.
          fetch-depth: 0  # Fetch the full history to avoid issues with git operations.

      # Step 3: Create a new branch and make 100 empty commits
      - name: Create empty commits on a new branch
        run: |
          git checkout --orphan Empty-commits  # Create a new branch without history.
          git rm -rf .  # Remove all files from the working directory to avoid accidental commits.
          for i in $(seq 1 100); do
            git commit --allow-empty -m "Empty commit #$i"  # Create an empty commit with a unique message.
          done

      # Step 4: Remove all files in the branch (after 100 empty commits)
      - name: Delete all files in the branch
        run: |
          git rm -rf .  # Remove all files from the working directory.
          git commit -m "Remove all files after 100 empty commits"  # Commit the file removals.

      # Step 5: Pull the latest changes from the remote branch (to avoid "behind" error)
      - name: Pull latest changes from remote
        run: |
          git pull origin Empty-commits || echo "No changes to pull"  # Pull changes from the remote Empty-commits branch.

      # Step 6: Push commits to the remote repository with GitHub token for authentication
      - name: Push commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication.
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git Empty-commits
