name: Push Empty Commits to Empty-commits Branch

on:
  push:
    branches:
      - main

jobs:
  empty-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create new branch and make 100 empty commits
        run: |
          git checkout -b Empty-commits  # Create and checkout the new branch
          for i in $(seq 1 100); do
            git commit --allow-empty -m "Empty commit #$i"
          done

      - name: Push commits to Empty-commits branch
        run: |
          git push origin Empty-commits  # Push the new branch with empty commits
