name: update-time  # Name of the workflow

# Trigger the workflow on the following events:
on:
  # Trigger on push events to the 'main' branch.
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch.
  
  # Trigger every 30 minutes based on cron schedule.
  schedule:
    - cron: "*/30 * * * *"  # This runs every 30 minutes.

jobs:
  # Define the job that will run on an Ubuntu machine.
  auto_commit:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner.

    steps:
      # Step 1: Checkout the repository to make changes.
      - uses: actions/checkout@v3  # Checkout the repository.
        with:
          persist-credentials: false  # Avoid storing credentials permanently.
          fetch-depth: 0  # Fetch the full history to avoid issues with git operations.

      # Step 2: Set date and time variables.
      - name: Set date and time variables  # Define a step to set date and time variables.
        run: |
          # Get the current date in 'YYYY-MM-DD' format.
          current_date=$(date +'%Y-%m-%d')  # Format the current date.
          # Get the current military time (24-hour format).
          military_time=$(date +'%H:%M:%S')  # Format the time in 24-hour format.
          # Get the current time in 12-hour format with AM/PM.
          normal_time=$(date +'%I:%M:%S %p')  # Format time in 12-hour format.
          # Get the current UTC time.
          utc_time=$(date -u +'%H:%M:%S UTC')  # Get UTC time in 24-hour format.
          
          # Set these variables for use in later steps.
          echo "DATE=$current_date" >> $GITHUB_ENV  # Set the current date as a GitHub environment variable.
          echo "MILITARY_TIME=$military_time" >> $GITHUB_ENV  # Set the military time.
          echo "NORMAL_TIME=$normal_time" >> $GITHUB_ENV  # Set the normal time.
          echo "UTC_TIME=$utc_time" >> $GITHUB_ENV  # Set UTC time.

      # Step 3: Create a JSON file with the time data and save it to time.json.
      - name: Write JSON into time.json  # Define a step to write the time data into a JSON file.
        run: |
          echo "{
            \"Date\": \"$DATE\",
            \"MilitaryTime\": \"$MILITARY_TIME\",
            \"NormalTime\": \"$NORMAL_TIME\",
            \"UTC\": \"$UTC_TIME\"
          }" | jq . > time.json  # Format and save the time data into time.json using jq.

      # Step 4: Commit the changes (time.json) to the repository.
      - name: Commit  # Define a step to commit the changes.
        run: |          
          git config --local user.email "RunarokHrafn@gmail.com"  # Set commit email.
          git config --local user.name "Runarok"  # Set commit author name.
          git add -A  # Stage all changes for commit.
          # Create a commit message with the date and UTC time.
          git commit -m "$DATE ($UTC_TIME)"  # Commit with a message that includes the date and UTC time.

      # Step 5: Push the commit to the remote repository.
      - name: Push  # Define a step to push the commit to GitHub.
        uses: ad-m/github-push-action@master  # Use GitHub Push Action to push changes.
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token to authenticate the push.
