name: Auto commit

on:
  push:
    branches:
      - Time
  schedule:
    - cron: "0 * * * *"  # Runs at the top of every hour (UTC)
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set time variables
        run: |
          # Get current time in military format (HHMM)
          MILITARY_TIME=$(date +'%H%M')
          # Get current time in normal format (hh:mm AM/PM)
          NORMAL_TIME=$(date +'%I:%M %p')
          
          # Save the values to GitHub Environment
          echo "military_time=${MILITARY_TIME}" >> $GITHUB_ENV
          echo "normal_time=${NORMAL_TIME}" >> $GITHUB_ENV

      - name: Write into Time.md
        run: |
          # Create or update Time.md with the current times
          echo "Military Time: ${{ env.military_time }}" > Time.md
          echo "Normal Time: ${{ env.normal_time }}" >> Time.md

      - name: Commit updated Time.md
        run: |
          git config --local user.email "RunarokHrafn@gmail.com"
          git config --local user.name "Runarok"
          git add Time.md
          git commit -m "Time Update with ${{ env.military_time }}"  # Commit message with the military time

      - name: Push changes
        run: |
          git push origin Time
